import InfinixHot8 from '../assets/infinix-hot-8.jpg';
import InfinixHot9 from '../assets/infinix-hot-9.jpg';
import InfinixHot10 from '../assets/infinix-hot-10.jpg';
import SamGS21 from '../assets/samsung-s21-5G.png';
import SamGS20 from '../assets/samsung-s20-5G.jpg';
import SamGS21Ultra from '../assets/samsung-s21-Ultra.jpg';
import SamGSA51 from '../assets/samsung-A51.jpg';
import Sam20Ultra from '../assets/samsung-Note20-Ultra-5G.jpg';
import SamZFold2 from '../assets/samsung-z-fold2.jpg';
import SamZFlip from '../assets/smasung-z-flip.png';
import TecnoPova from '../assets/tecno-pova.jpg';
import TecnoSpark6 from '../assets/tecno-spark6.jpg';
import TecnoSpark5Pro from '../assets/tecno-spark-5-pro.jpg';
import TecnoCamon16 from '../assets/tecno-camon16-premier.jpg';
import TecnoPop4 from '../assets/tecno-pop4.png';
import TecnoPouvoir4Pro from '../assets/tecno-pouvoir-4-pro.jpg';
import Iphone6 from '../assets/iphone-6.jpg';
import Iphone6S from '../assets/iphone-6S.jpg';
import Iphone6SPlus from '../assets/iphone-6S-plus.png';
import Iphone7Plus from '../assets/iphone7-plus.jpg';
import Iphone8 from '../assets/iphone8.jpg';
import IphoneSE from '../assets/iphone-SE.jpg';
import IphoneX from '../assets/iphoneX.jpg';
import IphoneXSMax from '../assets/iphoneXS-max.png';
import Iphone11ProMax from '../assets/iphone11-pro-max.png';
import Iphone12ProMax from '../assets/iphone12-pro-max.jpg';

const initialState = {
  phones: {
    mobiles: [
      {
        id: '1',
        name: 'Infinix Hot 8',
        category: 'Infinix',
        price: 40000,
        type: 'New and fairly-used',
        image: InfinixHot8,
        mainSpec: [
          { os: 'Android 9.0 (Pie), XOS 5.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 64GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '13 MP, f/1.8, 26mm (wide), 1/3.1", 1.12µm, PDAF, Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, f/2.0, 25mm (wide), LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '2',
        name: 'Infinix Hot 9',
        category: 'Infinix',
        price: 45000,
        type: 'New and fairly-used',
        image: InfinixHot9,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 32GB 3GB RAM, 64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'Triple-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '3',
        name: 'Infinix Hot 10',
        category: 'Infinix',
        price: 55000,
        type: 'New and fairly-used',
        image: InfinixHot10,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'T16 MP, (wide), PDAF, Quad-LED flash, HDR, panorama' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5200 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '4',
        name: 'Infinix Hot 8',
        category: 'Infinix',
        price: 40000,
        type: 'New and fairly-used',
        image: InfinixHot8,
        mainSpec: [
          { os: 'Android 9.0 (Pie), XOS 5.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 64GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '13 MP, f/1.8, 26mm (wide), 1/3.1", 1.12µm, PDAF, Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, f/2.0, 25mm (wide), LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '5',
        name: 'Infinix Hot 9',
        category: 'Infinix',
        price: 45000,
        type: 'New and fairly-used',
        image: InfinixHot9,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 32GB 3GB RAM, 64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'Triple-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '6',
        name: 'Infinix Hot 10',
        category: 'Infinix',
        price: 55000,
        type: 'New and fairly-used',
        image: InfinixHot10,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'T16 MP, (wide), PDAF, Quad-LED flash, HDR, panorama' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5200 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '7',
        name: 'Infinix Hot 8',
        category: 'Infinix',
        price: 40000,
        type: 'New and fairly-used',
        image: InfinixHot8,
        mainSpec: [
          { os: 'Android 9.0 (Pie), XOS 5.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 64GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '13 MP, f/1.8, 26mm (wide), 1/3.1", 1.12µm, PDAF, Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, f/2.0, 25mm (wide), LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '8',
        name: 'Infinix Hot 9',
        category: 'Infinix',
        price: 45000,
        type: 'New and fairly-used',
        image: InfinixHot9,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 32GB 3GB RAM, 64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'Triple-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '9',
        name: 'Infinix Hot 10',
        category: 'Infinix',
        price: 55000,
        type: 'New and fairly-used',
        image: InfinixHot10,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'T16 MP, (wide), PDAF, Quad-LED flash, HDR, panorama' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5200 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '10',
        name: 'Infinix Hot 8',
        category: 'Infinix',
        price: 40000,
        type: 'New and fairly-used',
        image: InfinixHot8,
        mainSpec: [
          { os: 'Android 9.0 (Pie), XOS 5.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 64GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '13 MP, f/1.8, 26mm (wide), 1/3.1", 1.12µm, PDAF, Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, f/2.0, 25mm (wide), LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '11',
        name: 'Infinix Hot 9',
        category: 'Infinix',
        price: 45000,
        type: 'New and fairly-used',
        image: InfinixHot9,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM, 32GB 3GB RAM, 64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'Triple-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '12',
        name: 'Infinix Hot 10',
        category: 'Infinix',
        price: 55000,
        type: 'New and fairly-used',
        image: InfinixHot10,
        mainSpec: [
          { os: 'Android 10, XOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: 'T16 MP, (wide), PDAF, Quad-LED flash, HDR, panorama' },
          { selfieCamera: '8 MP, (wide)' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 5200 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB' },
          { technology: 'GSM, HSPA, LTE' },
        ],
      },
      {
        id: '13',
        name: 'Samsung Galaxy S21 5G',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamGS21,
        mainSpec: [
          { os: 'Android 11, One UI 3.1' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM and/or eSIM, dual stand-by)' },
          { internal: '128GB 8GB RAM, 256GB 8GB RAM' },
          { card: 'No)' },
          { mainCamera: '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS, 64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom, LED flash, auto-HDR, panorama' },
          { selfieCamera: '10 MP, f/2.2, 26mm (wide), 1/3.24", 1.22µm, Dual Pixel PDAF, Dual video call, Auto-HDR' },
          { sensors: 'Fingerprint (under display, ultrasonic), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 4000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
      {
        id: '14',
        name: 'Samsung Galaxy S20 FE',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamGS20,
        mainSpec: [
          { os: 'Android 10, upgradable to Android 11, One UI 3.1' },
          { sim: 'Single SIM (Nano-SIM) or Hybrid Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM' },
          { card: 'microSDXC (uses shared SIM slot)' },
          { mainCamera: '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS, 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom, LED flash, auto-HDR, panorama' },
          { selfieCamera: '32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR' },
          { sensors: 'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Ion 4500 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
      {
        id: '15',
        name: 'Samsung Galaxy S21 Ultra',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamGS21Ultra,
        mainSpec: [
          { os: 'Android 11, One UI 3.1' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM and/or eSIM, dual stand-by)' },
          { internal: '128GB 12GB RAM, 256GB 12GB RAM, 512GB 16GB RAM' },
          { card: 'No' },
          { mainCamera: '108 MP, f/1.8, 24mm (wide), 1/1.33", 0.8µm, PDAF, Laser AF, OIS, 10 MP, f/4.9, 240mm (periscope telephoto), 1/3.24", 1.22µm, dual pixel PDAF, OIS, 10x optical zoom, LED flash, auto-HDR, panorama' },
          { selfieCamera: '40 MP, f/2.2, 26mm (wide), 1/2.8", 0.7µm, PDAF, Dual video call, Auto-HDR' },
          { sensors: 'Fingerprint (under display, ultrasonic), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
      {
        id: '16',
        name: 'Samsung Galaxy A51',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamGSA51,
        mainSpec: [
          { os: 'Android 10, upgradable to Android 11, One UI 3.0' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Hybrid Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '128GB 12GB RAM, 256GB 12GB RAM, 512GB 12GB RAM' },
          { card: 'microSDXC (uses shared SIM slot)' },
          { mainCamera: '108 MP, f/1.8, 26mm (wide), 1/1.33", 0.8µm, PDAF, Laser AF, OIS, 12 MP, f/3.0, 120mm (periscope telephoto), 1.0µm, PDAF, OIS, 5x optical zoom, 50x hybrid zoom, LED flash, auto-HDR, panorama' },
          { selfieCamera: '10 MP, f/2.2, 26mm (wide), 1/3.2", 1.22µm, Dual Pixel PDAF, Dual video call, Auto-HDR' },
          { sensors: 'Fingerprint (under display, ultrasonic), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 4500 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
      {
        id: '17',
        name: 'Samsung Galaxy Note20 Ultra 5G',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: Sam20Ultra,
        mainSpec: [
          { os: 'Android 10, upgradable to Android 11, One UI 3.1' },
          { sim: 'Single SIM (Nano-SIM) or Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF, 12 MP, f/2.2, 123˚ (ultrawide), LED flash, panorama, HDR' },
          { selfieCamera: '32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm, HDR' },
          { sensors: 'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass ANT+' },
          { batteryType: 'Li-Po 4000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '18',
        name: 'Samsung Galaxy Z Fold2',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamZFold2,
        mainSpec: [
          { os: 'Android 10, upgradable to Android 11, One UI 3.1' },
          { sim: 'Nano-SIM and/or eSIM' },
          { internal: '256GB 12GB RAM, 512GB 12GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS, 12 MP, f/2.4, 52mm (telephoto), 1/3.6", 1.0µm, PDAF, OIS, 2x optical zoom, LED flash, HDR, panorama' },
          { selfieCamera: '10 MP, f/2.2, 26mm (wide), 1/3", 1.22µm, HDR' },
          { sensors: 'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Po 4500 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
      {
        id: '19',
        name: 'Samsung Galaxy Z Flip',
        category: 'Samsung',
        price: 55000,
        type: 'New and fairly-used',
        image: SamZFlip,
        mainSpec: [
          { os: 'Android 10, upgradable to Android 11, One UI 3.0' },
          { sim: 'Nano-SIM, eSIM' },
          { internal: '256GB 8GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS, LED flash, HDR, panorama' },
          { selfieCamera: '10 MP, f/2.4, 26mm (wide), 1.22µm, HDR' },
          { sensors: 'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Po 3300 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '20',
        name: 'Tecno Pova',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoPova,
        mainSpec: [
          { os: 'Android 10, HIOS 7.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '13 MP or 16 MP, f/1.9, (wide), PDAF, 2 MP, (macro), Quad-LED flash' },
          { selfieCamera: '8 MP, f/2.0, Dual-LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity, compass' },
          { batteryType: 'Li-Po 6000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '21',
        name: 'Tecno Spark 6',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoSpark6,
        mainSpec: [
          { os: 'Android 10, HIOS 7.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '64GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '16 MP, PDAF, 2 MP, (macro), Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, Dual-LED flash, HDR' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '22',
        name: 'Tecno Camon 16 Premier',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoCamon16,
        mainSpec: [
          { os: 'Android 10, HIOS 6.0' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '128GB 8GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '64 MP, f/1.9, 26mm (wide), 1/1.73", 0.8µm, PDAF, 8 MP, f/2.3, 119˚ (ultrawide), 1/4.0", 1.12µm, Penta-LED flash, panorama, HDR' },
          { selfieCamera: '48 MP, f/2.2, 23mm (wide), 1/2.0", 0.8µm, 8 MP, f/2.2, 105˚ (ultrawide), 1/4.0", 1.12µm, Dual-LED flash, HDR' },
          { sensors: 'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 4500 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '23',
        name: 'Tecno Pop 4',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoPop4,
        mainSpec: [
          { os: 'Android 10 (Go edition), HIOS' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by)' },
          { internal: '32GB 2GB RAM' },
          { card: 'microSDXC' },
          { mainCamera: '5 MP, Dual-LED flash' },
          { selfieCamera: '8 MP, LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA' },
        ],
      },
      {
        id: '24',
        name: 'Tecno Spark 5 Pro',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoSpark5Pro,
        mainSpec: [
          { os: 'Android 10, HIOS 6.1' },
          { sim: 'Dual SIM (Nano-SIM, dual stand-by))' },
          { internal: '64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '16 MP, f/1.8, PDAF, Quad-LED flash, panorama, HDR' },
          { selfieCamera: '8 MP, f/2.0, (wide), Dual-LED flash, HDR' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity' },
          { batteryType: 'Li-Po 5000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '25',
        name: 'Tecno Pouvoir 4 Pro',
        category: 'Tecno',
        price: 55000,
        type: 'New and fairly-used',
        image: TecnoPouvoir4Pro,
        mainSpec: [
          { os: 'Android 10, HIOS 6.0' },
          { sim: 'Dual SIM' },
          { internal: '64GB 4GB RAM, 128GB 6GB RAM' },
          { card: 'microSDXC (dedicated slot)' },
          { mainCamera: '16 MP, f/1.9, (wide), AF, 5 MP, f/2.2, (macro), Quad-LED flash' },
          { selfieCamera: '16 MP, f/2.0, 27mm (wide), Dual-LED flash' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity' },
          { batteryType: 'Li-Po 6000 mAh, non-removable' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '26',
        name: 'Iphone 6',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone6,
        mainSpec: [
          { os: 'iOS 8, upgradable to iOS 12.4.6' },
          { sim: 'Nano-SIM' },
          { internal: '16GB 1GB RAM, 32GB 1GB RAM, 64GB 1GB RAM, 128GB 1GB RAM' },
          { card: 'No' },
          { mainCamera: '8 MP, f/2.2, 29mm (standard), 1/3", 1.5µm, PDAF, Dual-LED dual-tone flash, HDR' },
          { selfieCamera: '1.2 MP, f/2.2, 31mm (standard), face detection, HDR, FaceTime over Wi-Fi or Cellular' },
          { sensors: 'Fingerprint (rear-mounted), accelerometer, proximity' },
          { batteryType: 'Li-Po 1810 mAh, non-removable (6.9 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '27',
        name: 'Iphone 6S',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone6S,
        mainSpec: [
          { os: 'iOS 9, upgradable to iOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '16GB 2GB RAM, 32GB 2GB RAM, 64GB 2GB RAM, 128GB 2GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/2.2, 29mm (standard), 1/3", 1.22µm, PDAF, Dual-LED dual-tone flash, HDR' },
          { selfieCamera: '5 MP, f/2.2, 31mm (standard), Face detection, HDR, panorama' },
          { sensors: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 1715 mAh, non-removable (6.91 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '28',
        name: 'Iphone 6S Plus',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone6SPlus,
        mainSpec: [
          { os: 'iOS 9, upgradable to iPadOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '16GB 2GB RAM, 32GB 2GB RAM, 64GB 2GB RAM, 128GB 2GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/2.2, 29mm (standard), 1/3", 1.22µm, PDAF, OIS, Dual-LED dual-tone flash, HDR' },
          { selfieCamera: '5 MP, f/2.2, 31mm (standard), Face detection, HDR, panorama' },
          { sensors: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 2750 mAh, non-removable (10.45 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '29',
        name: 'IPhone SE (1st generation)',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: IphoneSE,
        mainSpec: [
          { os: 'iOS 9.3.2, upgradable to iOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '16GB 2GB RAM, 32GB 2GB RAM, 64GB 2GB RAM, 128GB 2GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/2.2, 29mm (standard), 1/3", 1.22µm, PDAF, Dual-LED dual-tone flash, HDR' },
          { selfieCamera: '1.2 MP, f/2.4, 31mm (standard), Face detection, HDR, panorama' },
          { sensors: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass' },
          { batteryType: 'Li-Po 1624 mAh, non-removable (6.21 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '30',
        name: 'IPhone 7 Plus',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone7Plus,
        mainSpec: [
          { os: 'iOS 10.0.1, upgradable to iOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '32GB 3GB RAM, 128GB 3GB RAM, 256GB 3GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 28mm (wide), 1/3", PDAF, OIS, Quad-LED dual-tone flash, HDR' },
          { selfieCamera: '7 MP, f/2.2, 32mm (standard), Face detection, HDR' },
          { sensors: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 2900 mAh, non-removable (11.1 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '31',
        name: 'IPhone 8',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone8,
        mainSpec: [
          { os: 'iOS 11, upgradable to iOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '64GB 2GB RAM, 128GB 2GB RAM, 256GB 2GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 28mm (wide), PDAF, OIS, Quad-LED dual-tone flash, HDR' },
          { selfieCamera: '7 MP, f/2.2, Face detection, HDR, panorama' },
          { sensors: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 1821 mAh, non-removable (6.96 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '32',
        name: 'IPhone X',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: IphoneX,
        mainSpec: [
          { os: 'iOS 11.1.1, upgradable to iOS 14.4.2' },
          { sim: 'Nano-SIM' },
          { internal: '64GB 3GB RAM, 256GB 3GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 28mm (wide), 1/3", 1.22µm, dual pixel PDAF, OIS, Quad-LED dual-tone flash, HDR (photo/panorama), panorama, HDR' },
          { selfieCamera: '7 MP, f/2.2, 32mm (standard), SL 3D, (depth/biometrics sensor)' },
          { sensors: 'Face ID, accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 2716 mAh, non-removable (10.35 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / HSPA / LTE' },
        ],
      },
      {
        id: '33',
        name: 'IPhone XS Max',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: IphoneXSMax,
        mainSpec: [
          { os: 'iOS 12, upgradable to iOS 14.4.2' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM, dual stand-by) - for China' },
          { internal: '64GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS, Quad-LED dual-tone flash, HDR (photo/panorama)' },
          { selfieCamera: '7 MP, f/2.2, 32mm (standard)' },
          { sensors: 'Face ID, accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 3174 mAh, non-removable (12.08 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '34',
        name: 'IPhone 11 Pro Max',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone11ProMax,
        mainSpec: [
          { os: 'iOS 13, upgradable to iOS 14.4.2' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM, dual stand-by) - for China' },
          { internal: '64GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.8, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS, Dual-LED dual-tone flash, HDR (photo/panorama)' },
          { selfieCamera: '12 MP, f/2.2, 23mm (wide), 1/3.6", HDR' },
          { sensors: 'Face ID, accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 3969 mAh, non-removable (15.04 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE' },
        ],
      },
      {
        id: '35',
        name: 'IPhone 12 Pro Max',
        category: 'Apple',
        price: 55000,
        type: 'New and fairly-used',
        image: Iphone12ProMax,
        mainSpec: [
          { os: 'iOS 14.1, upgradable to iOS 14.4.2' },
          { sim: 'Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM, dual stand-by) - for China' },
          { internal: '128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM' },
          { card: 'No' },
          { mainCamera: '12 MP, f/1.6, 26mm (wide), 1.7µm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.2, 65mm (telephoto), 1/3.4", 1.0µm, PDAF, OIS, 2.5x optical zoom, Dual-LED dual-tone flash, HDR (photo/panorama)' },
          { selfieCamera: '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor), HDR' },
          { sensors: 'Face ID, accelerometer, gyro, proximity, compass, barometer' },
          { batteryType: 'Li-Ion 3687 mAh, non-removable (14.13 Wh)' },
          { others: 'WLAN, Bluetooth, GPS, Radio, USB, NFC' },
          { technology: 'GSM / CDMA / HSPA / EVDO / LTE / 5G' },
        ],
      },
    ],
  },
  addedItems: [],
  total: 0,
};

export default initialState;
